FROM registry.ng.bluemix.net/ibmliberty:javaee7
COPY ./acmeair-fs/server.xml /config/

RUN installUtility install --acceptLicense defaultServer

EXPOSE 80
ENV VCAP_APP_PORT=80
ENV SERVICE_NAME=flight

ADD ./acmeair-fs/build/libs/acmeair-fs-2.0.0-SNAPSHOT.war /config/apps/