FROM acmeair-mono-base-minimal

ARG CONFIG_DIRECTORY
ARG WAR_FILE

COPY --chown=1001:0 ${CONFIG_DIRECTORY}/* /opt/ol/wlp/usr/servers/defaultServer/
COPY --chown=1001:0 ${WAR_FILE} /opt/ol/wlp/usr/servers/defaultServer/apps/

ARG VERBOSE=true
RUN populate_scc.sh -i 1

# Set SCC to readonly
ENV OPENJ9_JAVA_OPTIONS="-XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningGcOnIdle -Xshareclasses:name=liberty,readonly,cacheDir=/output/.classCache -Dosgi.checkConfiguration=false"



