FROM acmeair-mono-base-minimal-no-scc

ARG CONFIG_DIRECTORY
ARG WAR_FILE

COPY --chown=1001:0 ${CONFIG_DIRECTORY}/* /opt/ol/wlp/usr/servers/defaultServer/
COPY --chown=1001:0 ${WAR_FILE} /opt/ol/wlp/usr/servers/defaultServer/apps/

# Set SCC to readonly
ENV OPENJ9_JAVA_OPTIONS="-XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningGcOnIdle -Xshareclasses:none -Dosgi.checkConfiguration=false"



