FROM acmeair-mono-base-minimal

ARG WAR_FILE

COPY --chown=1001:0 src/main/liberty/config/* /opt/ol/wlp/usr/servers/defaultServer/
COPY --chown=1001:0 ${WAR_FILE} /opt/ol/wlp/usr/servers/defaultServer/apps/

# start/stop to set conig cache
RUN server start && server stop




