### CREATE SMALL JRE IMAGE ###

FROM ibmsemeruruntime/open-11-jdk:focal-jdk-latest as buildjre

COPY --chown=1001:0 java_modules.txt /tmp/java_modules.txt

# create the minified JRE using jlink
RUN /opt/java/openjdk/bin/jlink --no-header-files \
           --no-man-pages --compress=2 \
           --strip-debug \
           --add-modules $(cat /tmp/java_modules.txt) \
           --output /opt/jdk11-minified


### CREATE SMALL LIBERTY IMAGE ###
FROM open-liberty:kernel-slim-java11-openj9 as buildLiberty_minify

# Install unzip; needed to unzip Open Liberty
USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends unzip
USER 1001

# Copy in a server.xml to start server with correct features set
COPY --chown=1001:0 src/main/liberty/config/server.xml /config/server.xml
RUN features.sh

# Create a minified openliberty package for use in final image
RUN /opt/ol/wlp/bin/server package --archive=/tmp/ol_minified.zip --include=minify --os=Linux

RUN ls -l /tmp/ol_minified.zip

WORKDIR /tmp

RUN unzip /tmp/ol_minified.zip -d /tmp/ol

### CREATE SCC ###
FROM registry.access.redhat.com/ubi8/ubi-minimal as buildscc

### copy in the minified java11 jre
COPY --chown=1001:0 --from=buildjre /opt/jdk11-minified /opt/jdk11-minified

## copy in the minified package of open liberty
COPY --chown=1001:0 --from=buildLiberty_minify /tmp/ol /opt/ol/

# Config
COPY --chown=1001:0 src/main/liberty/config/server.xml /opt/ol/wlp/usr/servers/defaultServer/server.xml
COPY --chown=1001:0 target/acmeair-java-2.0.0-SNAPSHOT.war /opt/ol/wlp/usr/servers/defaultServer/apps/

ENV JAVA_HOME=/opt/jdk11-minified
ENV OPENJ9_JAVA_OPTIONS="-XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningGcOnIdle -Xshareclasses:name=liberty,cacheDir=/output/.scc -Dosgi.checkConfiguration=false"

#### Starting the server will populate the SCC
ENV PATH=/opt/ol/wlp/bin:$PATH
RUN server start && server stop && server start && server stop

### FINAL BASE IMAGE ###

### Get the ubi
FROM registry.access.redhat.com/ubi8/ubi-minimal

### copy in the minified java11 jre
COPY --chown=1001:0 --from=buildjre /opt/jdk11-minified /opt/jdk11-minified

## copy in the minified package of open liberty
COPY --chown=1001:0 --from=buildLiberty_minify /tmp/ol /opt/ol/

## copy in the populated SCC from build_scc
COPY --chown=1001:0 --from=buildscc /output/.scc /output/.scc

# Config
COPY --chown=1001:0 src/main/liberty/config/server.xml /opt/ol/wlp/usr/servers/defaultServer/server.xml

ENV PATH=/opt/ol/wlp/bin:$PATH
ENV JAVA_HOME=/opt/jdk11-minified
ENV OPENJ9_JAVA_OPTIONS="-XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningGcOnIdle -Xshareclasses:name=liberty,cacheDir=/output/.scc,readonly -Dosgi.checkConfiguration=false"

CMD ["/opt/ol/wlp/bin/server", "run", "defaultServer"]
