### CREATE SMALL LIBERTY IMAGE ###
FROM open-liberty:kernel-slim-java11-openj9 as buildLiberty_minify

# Install unzip; needed to unzip Open Liberty
USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends unzip
USER 1001

# Copy in a server.xml to start server with correct features set
COPY --chown=1001:0 src/main/liberty/config /config
RUN features.sh

# Create a minified openliberty package for use in final image
RUN /opt/ol/wlp/bin/server package --archive=/tmp/ol_minified.zip --include=minify --os=Linux

RUN ls -l /tmp/ol_minified.zip

WORKDIR /tmp

RUN unzip -q /tmp/ol_minified.zip -d /tmp/ol

FROM ibmsemeruruntime/open-11-jdk:focal-jdk-latest as buildjre

ARG WAR_FILE

RUN apt-get update \
    && apt-get install -y --no-install-recommends unzip

COPY --chown=1001:0 --from=buildLiberty_minify /tmp/ol /opt/ol/
COPY --chown=1001:0 ${WAR_FILE} /tmp
COPY getJDeps.sh /
COPY java_modules_append.txt /
COPY java_modules_exclude.txt /

RUN cd /tmp && unzip $(basename ${WAR_FILE})
RUN cd / && /getJDeps.sh /opt/ol/wlp/lib --jars
RUN /getJDeps.sh /tmp/WEB-INF/lib --jars --append
RUN /getJDeps.sh /tmp/WEB-INF/classes --append
RUN echo -n "," >> /java_modules.txt && cat /java_modules_append.txt >> /java_modules.txt
RUN cat /java_modules.txt

RUN /opt/java/openjdk/bin/jlink --no-header-files \
           --no-man-pages --compress=2 \
           --strip-debug \
           --add-modules $(cat /java_modules.txt) \
           --output /opt/jdk11-minified

### CREATE SCC ###
FROM registry.access.redhat.com/ubi8/ubi-minimal as buildscc

ARG WAR_FILE

### copy in the minified java11 jre
COPY --chown=1001:0 --from=buildjre /opt/jdk11-minified /opt/jdk11-minified

## copy in the minified package of open liberty
COPY --chown=1001:0 --from=buildLiberty_minify /tmp/ol /opt/ol/

# Config
COPY --chown=1001:0 src/main/liberty/config/* /opt/ol/wlp/usr/servers/defaultServer/
COPY --chown=1001:0 ${WAR_FILE}  /opt/ol/wlp/usr/servers/defaultServer/apps/

ENV JAVA_HOME=/opt/jdk11-minified
ENV OPENJ9_JAVA_OPTIONS="-XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningGcOnIdle -Xshareclasses:name=liberty,cacheDir=/output/.scc -Dosgi.checkConfiguration=false"

#### Starting the server will populate the SCC
ENV PATH=/opt/ol/wlp/bin:$PATH
RUN server start && server stop && server start && server stop

### FINAL BASE IMAGE ###

### Get the ubi
FROM registry.access.redhat.com/ubi8/ubi-minimal

### copy in the minified java11 jre
COPY --chown=1001:0 --from=buildjre /opt/jdk11-minified /opt/jdk11-minified

## copy in the minified package of open liberty
COPY --chown=1001:0 --from=buildLiberty_minify /tmp/ol /opt/ol/

## copy in the populated SCC from build_scc
COPY --chown=1001:0 --from=buildscc /output/.scc /output/.scc

# Config
COPY --chown=1001:0 src/main/liberty/config/* /opt/ol/wlp/usr/servers/defaultServer/

ENV PATH=/opt/ol/wlp/bin:$PATH
ENV JAVA_HOME=/opt/jdk11-minified
ENV OPENJ9_JAVA_OPTIONS="-XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningGcOnIdle -Xshareclasses:name=liberty,cacheDir=/output/.scc,readonly -Dosgi.checkConfiguration=false"

CMD ["/opt/ol/wlp/bin/server", "run", "defaultServer"]
