apiVersion: apps/v1 #extensions/v1beta1
kind: Deployment
metadata:
  name: acmeair-monolithic-java-deployment
  namespace: acmeair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acmeair
  template:
    metadata:
      labels:
        app: acmeair
        tier: monolithic
    spec:
      containers:
      - name: acmeair-java
        image: quay.io/cbade_cs/acmeair_test:acmeair-demo #IMAGE_NAME
        imagePullPolicy: Always
        env:
        - name: MONGO_MANUAL
          value: "true"
        - name: MONGO_HOST
          value: "localhost"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DBNAME
          value: "acmeair"
        - name: MONGO_USER
          value: "user"
        - name: MONGO_PASSWORD
          value: "password"
        resources:
          requests:
            cpu: "700m"
