apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: acmeair-java-autoscaler
  namespace: acmeair
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    kind: Deployment
    name: acmeair-monolithic-java-deployment
  targetCPUUtilizationPercentage: 80
