apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: acmeair # ghost
  #namespace: acmeair #ghost
resources:
- 0_project.yaml
- 1_app.yaml
- 2_service.yaml
- 3_route.yaml
- 4_autoscaler.yaml
  #- sec.yaml #5_secret.sh
- 6_pvc.yaml
- 7_db.yaml
- 8_db_service.yaml
secretGenerator:
- name: mongodb-creds #example-secret-2
  literals:
  - username=admin
  - password=pass1234
